export const REQUEST_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_AI: 'PENDING_AI',
  PENDING_MANAGER: 'PENDING_MANAGER',
  IN_CORRECTION: 'IN_CORRECTION',
  PENDING_FINANCE: 'PENDING_FINANCE',
  IN_PAYMENT: 'IN_PAYMENT',
  PAID: 'PAID',
  REJECTED_AI: 'REJECTED_AI',
  REJECTED_MANAGER: 'REJECTED_MANAGER',
  REJECTED_FINANCE: 'REJECTED_FINANCE',
  CANCELLED: 'CANCELLED'
}

export const PAYMENT_STATUS = {
  SCHEDULED: 'SCHEDULED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
}
